# Generated by Django 4.0.1 on 2022-01-24 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academybot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='total_payment',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_price',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
