# Generated by Django 4.0.1 on 2022-01-25 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academybot', '0002_student_total_payment_alter_courses_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academybot.courses'),
            preserve_default=False,
        ),
    ]
